version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "/templates/basic-js"
    schedule:
      interval: "daily"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "/templates/basic-ts"
    schedule:
      interval: "daily"
    versioning-strategy: increase
  - package-ecosystem: "npm"
    directory: "/templates/react-js"
    schedule:
      interval: "daily"
    versioning-strategy: increase
