version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase-if-necessary
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
