env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
globals:
  PAGE_PATH: readonly
  geofs: readonly
  ui: readonly
  flight: readonly
  objects: readonly
  controls: readonly
  weather: readonly
  audio: readonly
  multiplayer: readonly
  instruments: readonly
  absMin: readonly
  span: readonly
  boundHours24: readonly
  fixAngle: readonly
  fixAngle360: readonly
  fixAngles360: readonly
  fixAngles: readonly
  exponentialSmoothingV3: readonly
  exponentialSmoothing: readonly
  getBuildingCollision: readonly
  xyz2lla: readonly
  xy2ll: readonly
  lla2xyz: readonly
  ll2xy: readonly
  clamp: readonly
  geoDecodeLocation: readonly
  lookAt: readonly
  getURLParameters: readonly
  clone: readonly
  PID: readonly
  Overlay: readonly
  rigidBody: readonly
  Object3D: readonly
  Indicator: readonly
  GlassPanel: readonly
plugins:
  - react
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
rules:
  eqeqeq:
    - error
settings:
  react:
    version: detect
